// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzfAMPiPWFZaBR0b5EjSyYemZTaIU0cVc',
    appId: '1:560318998001:web:0a38c2df6bcfe805d95050',
    messagingSenderId: '560318998001',
    projectId: 'homzesdb',
    authDomain: 'homzesdb.firebaseapp.com',
    storageBucket: 'homzesdb.firebasestorage.app',
    measurementId: 'G-S88XZN5KYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAArsbn7wo8LWJOTkYBaVkg-PVnBX8oSho',
    appId: '1:560318998001:android:7d7389888bb35df4d95050',
    messagingSenderId: '560318998001',
    projectId: 'homzesdb',
    storageBucket: 'homzesdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqThgjGiu9X5UeTHxbdaL0aALy_NgIfjI',
    appId: '1:560318998001:ios:2f12de2db16d6cebd95050',
    messagingSenderId: '560318998001',
    projectId: 'homzesdb',
    storageBucket: 'homzesdb.firebasestorage.app',
    iosBundleId: 'com.example.homzes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqThgjGiu9X5UeTHxbdaL0aALy_NgIfjI',
    appId: '1:560318998001:ios:2f12de2db16d6cebd95050',
    messagingSenderId: '560318998001',
    projectId: 'homzesdb',
    storageBucket: 'homzesdb.firebasestorage.app',
    iosBundleId: 'com.example.homzes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzfAMPiPWFZaBR0b5EjSyYemZTaIU0cVc',
    appId: '1:560318998001:web:db6d603f4801d80ad95050',
    messagingSenderId: '560318998001',
    projectId: 'homzesdb',
    authDomain: 'homzesdb.firebaseapp.com',
    storageBucket: 'homzesdb.firebasestorage.app',
    measurementId: 'G-JQ5ZKJEHDY',
  );
}
